// Generated by CoffeeScript 1.4.0
(function() {

  App.Freebase = {
    search: function(query_string, _done, _fail, _complete) {
      return $.get('https://www.googleapis.com/freebase/v1/search', {
        query: query_string,
        lang: 'en'
      }).done(_done).fail(_fail).complete(_complete);
    },
    fetchExtraInformation: function(ids, _done, _fail, _complete) {}
  };

}).call(this);
