// Generated by CoffeeScript 1.4.0
(function() {

  App.Renderer = {
    BOX_HTML: '<span><%= title %> (<%= category %>)</span><hr /><img src="<%= image_src %>">',
    renderBoxes: function($container, data) {
      var boxes, datum, _i, _len;
      if (!$container.length) {
        return;
      }
      if (!(data.length > 0)) {
        return;
      }
      $container.html('');
      boxes = [];
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        datum = data[_i];
        boxes.push(this.renderBox(datum));
      }
      $container.append(boxes);
      return this._masonify($container);
    },
    renderBox: function(datum) {
      var _ref;
      return $('<div/>', {
        'class': 'search-result',
        html: _.template(this.BOX_HTML, {
          title: datum.name,
          category: (_ref = datum.notable) != null ? _ref.name : void 0,
          image_src: App.Freebase.BASE_IMAGE_URL + datum.id
        })
      });
    },
    _masonify: function($container) {
      return $container.imagesLoaded(function() {
        $container.masonry;
        return {
          itemSelector: '.search-result',
          columnWidth: 100
        };
      });
    }
  };

}).call(this);
